destinationVolume: /mnt/external-drive
excludedVolumes:
  - /mnt/external-drive
supportedExtensions:
  - .jpg
  - .jpeg
notifications:
  enabled: true
  userKey: example-user-key
  apiKey: example-api-key
