- name: Install photo-sync
  hosts: all
  become: yes
  vars_files: ../vars.yaml
  tasks:
    - name: Download artifact
      get_url:
        url: "https://github.com/JDLK7/photo-sync/releases/download/{{ photo_sync.version }}/photo-sync-linux-armv7.tar.gz"
        dest: /tmp/photo-sync-linux-armv7.tar.gz
    
    - name: Create destination folder
      file:
        state: directory
        path: /opt/photo-sync

    - name: Extract binary
      unarchive:
        remote_src: yes
        src: /tmp/photo-sync-linux-armv7.tar.gz
        dest: /opt/photo-sync
        extra_opts: [--strip-components=3]

    - name: Lay down config
      blockinfile:
        path: /etc/photo-sync/config.yaml
        block: |
          excludedVolumes:
            - /mnt/josehdd
          destinationVolume: /mnt/josehdd/media
          supportedExtensions:
            - .jpg
            - .jpeg
            - .mp4
            - .avi
          notifications:
            enabled: true
            userKey: {{ photo_sync.user_key }}
            apiKey: {{ photo_sync.api_key }}

    - name: Create service
      blockinfile:
        path: /etc/systemd/system/photo-sync.service
        block: |
          [Unit]
          Description=Media sync agent
          Documentation=https://github.com/JDLK7/photo-sync
          After=network-online.target

          [Service]
          User=root
          Restart=on-failure

          Environment="CONFIG_PATH=/etc/photo-sync/config.yaml"
          ExecStart=/opt/photo-sync/photo-sync

          [Install]
          WantedBy=multi-user.target
    
    - name: Start service
      service:
        name: photo-sync
        enabled: yes
        state: started
