---
- name: Configure Samba
  hosts: all
  become: true
  vars_files: ../vars.yaml 
  tasks:
    - name: Install packages
      apt:
        update_cache: yes
        pkg:
          - samba
          - samba-common-bin
    
    - name: Samba config
      blockinfile:
        path: /etc/samba/smb.conf
        block: |
          [media]
            path = {{ samba.volume }}
            valid users = {{ samba.user }}
            writeable = yes
            create mask = 0777
            directory mask = 0777
            public = no
    
    - name: Create users
      command: smbpasswd -a {{ samba.user }} -w {{ samba.password }}

    - name: Restart samba service
      service:
        name: smbd
        state: restarted
