ssh_key_filename: id_rsa_raspberry
hostname: raspberrypi
users:
  - photosync
prometheus:
  version: 2.22.0
node_exporter:
  version: 1.0.1
samba:
  volume: /mnt/external-drive/media
  user: photosync
  password: changeme
photo_sync:
  version: v0.2.0
  user_key: example-user-key
  api_key: example-api-key
packages:
  # Z shell
  - git
  - zsh
  # utilities
  - tree
  - jq
  # hostname
  - avahi-daemon
  # others
  - grafana
