name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    # FIXME: tests are not working right now
    # - name: Test
    #   run: go test -v ./...

    - name: Build artifacts
      if: startsWith(github.ref, 'refs/tags/')
      run: make dist

    - name: Upload artifacts
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          dist/photo-sync-linux-armv7.tar.gz
          dist/photo-sync-linux-amd64.tar.gz
          dist/photo-sync-darwin-amd64.tar.gz
