name: Publish

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build artifacts
      run: make dist

    - name: Upload artifacts
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          dist/photo-sync-linux-armv7.tar.gz
          dist/photo-sync-linux-amd64.tar.gz
          dist/photo-sync-darwin-amd64.tar.gz

    # - name: Upload Linux armv7 artifact
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: ./dist/dist/photo-sync-linux-armv7.tar.gz
    #     asset_name: photo-sync-linux-armv7.tar.gz
    #     asset_content_type: application/gzip

    # - name: Upload Linux amd64 artifact
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: ./dist/dist/photo-sync-linux-amd64.tar.gz
    #     asset_name: photo-sync-linux-amd64.tar.gz
    #     asset_content_type: application/gzip

    # - name: Upload Darwin amd64 artifact
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: ./dist/dist/photo-sync-darwin-amd64.tar.gz
    #     asset_name: photo-sync-darwin-amd64.tar.gz
    #     asset_content_type: application/gzip

